require: rubocop-rspec

# Remove these configuration records
# one by one as the offenses are removed from the code base.

Metrics/AbcSize:
  Max: 21 # Goal: 15

Metrics/CyclomaticComplexity:
  Max: 8 # Goal: 6

Metrics/PerceivedComplexity:
  Max: 9 # Goal: 7

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - spec/paper_trail/associations/belongs_to_spec.rb
    - spec/paper_trail/associations/habtm_spec.rb
    - spec/paper_trail/associations/has_many_through_spec.rb

RSpec/NestedGroups:
  Exclude:
    - spec/paper_trail/associations/belongs_to_spec.rb
    - spec/paper_trail/associations/habtm_spec.rb
    - spec/paper_trail/associations/has_many_through_spec.rb
    - spec/paper_trail/model_spec.rb

# It may be possible for us to use safe_load, but we'd have to pass the
# safelists, like `whitelist_classes` into our serializer, and the serializer
# interface is a public API, so that would be a breaking change.
Security/YAMLLoad:
  Enabled: false
