language: ruby
cache: bundler

rvm:
  - 2.4

env:
  global:
    - TRAVIS=true
  matrix:
    - DB=mysql

sudo: false

services:
  - mysql

gemfile:
  - gemfiles/ar_5.0.gemfile

before_install:
  - gem update bundler

matrix:
  fast_finish: true

