language: ruby
cache: bundler

rvm:
  - 2.4

env:
  global:
    - TRAVIS=true
  matrix:
    - DB=mysql

sudo: false

before_install:
  - gem update bundler

gemfile:
  - gemfiles/ar_5.0.gemfile
matrix:
  fast_finish: true

services:
  - mysql
